spring.application.name=anthilgroupwebsite
# ===============================
# EMAIL CONFIGURATION
# ===============================

spring.mail.username=noreply.anthillgroup@gmail.com
spring.mail.password=gzdfcssaoyltbssk
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# OPTIONAL (Recommended)
# ===============================

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Disable default DB auto-config (since not using DB)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8080